### ISSUE TITLE
Materials on gSLOPE

### ISSUE THREAD

**Issue by mstaniak** [mmaku/MT#1]
Hi,

I would like to write a complete gSLOPE package with the students attending my "Software development with R" class, would you like to help by sharing some materials about the method? Your thesis would be very appreciate (-; 
if you can/want to help, please send me an e-mail

**Comment by mstaniak** [comment]
I got your thesis now, btw

**Comment by mmaku** [comment]
Cześć,
przepraszam, byłem w Norwegii, dopiero wczoraj wróciłem i ogarniam życie, miałem małe zamieszanie.
Mogę ze wszystkim pomóc, co Cię interesuje?

Pozdrawiam, Michał 

On 11 March 2020 15:21:20 CET, Mateusz Staniak <notifications@github.com> wrote:
>Hi,
>
>I would like to write a complete gSLOPE package with the students
>attending my "Software development with R" class, would you like to
>help by sharing some materials about the method? Your thesis would be
>very appreciate (-; 
>if you can/want to help, please send me an e-mail
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mmaku/MT/issues/1

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mstaniak** [comment]
Cześć, 
mam nadzieję, że wszystko gra u Ciebie (: 
Studenci mają jakieś pytania i napiszą tutaj 
@KrystynaGrzesiak

**Comment by KrystynaGrzesiak** [comment]
Cześć, 
jeśli nie masz nic przeciwko, to chcielibyśmy skorzystać z Twojego kodu przy tworzeniu pakietu z grafowym slope. Poza tym mamy kilka pytań odnośnie Twojej pracy i samego kodu. Czy znalazłbyś chwilę, by rozwiać nasze wątpliwości? Jaka forma kontaktu byłaby dla Ciebie najwygodniejsza?

Pozdrawiam, Krysia

**Comment by mmaku** [comment]
Cześć,
jasne, zapraszam do korzystania, w razie potrzeby jestem do Waszej dyspozycji.
Co do kontaktu, to może być tutaj, może też być mailowo na m(kropeczka)makowski(małpa)aol[znów kropka]com, możecie też mnie znaleźć na portalach społecznościowych, możemy się nawet umówić na telekonfe. :) 
Proszę tylko, abyście w przyszłości zaznaczyli, że opieraliście się na mojej pracy.

Pozdrawiam, Michał

**Comment by mstaniak** [comment]
Hej,

bez obaw, będziesz autorem pakietu i nic się nie wydarzy bez Twojej wiedzy (: 
Prof. Bogdan chciała po prostu owinięcia gSLOPE'a w pakiet, więc na moich zajęciach łączymy potrzebne z pożytecznym.

Pozdr.
MS

**Comment by mmaku** [comment]
Na bycie autorem autorem to chyba nie zasłużyłem, ale krótka wzmianka gdzieś na końcu mnie zadowoli. :)

**Comment by mstaniak** [comment]
Oczywiste, że będziesz autorem, jeśli pakiet powstanie (-;
